name: Build

on: [push]

jobs:
  build:
    name: Build documents
    runs-on: ubuntu-latest

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Install TeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive tex-gyre texlive-luatex lmodern  texlive-xetex texlive-latex-base texlive-latex-extra texlive-lang-polish texlive-generic-recommended texlive-fonts-recommended texlive-fonts-extra texlive-extra-utils texlive-science latexmk xzdec
      - name: Build docs
        run: |
          cd docs
          latexmk *.tex
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/*.pdf

  release:
    name: Publish documents
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: docs
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./*.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
